# Generated by Django 5.2.13 on 2026-06-02 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20200507_1449'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
