# Generated by Codex on 2026-06-02

from django.db import migrations, models
import django.db.models.deletion


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('pybo', 'Category')
    Question = apps.get_model('pybo', 'Question')

    defaults = [
        ('질문답변', 'qna', '질문과 답변을 나누는 게시판입니다.'),
        ('강좌', 'lecture', '강좌 게시판입니다.'),
        ('자유게시판', 'free', '자유롭게 글을 남기는 게시판입니다.'),
    ]
    categories = {}
    for name, slug, description in defaults:
        category, _ = Category.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'description': description},
        )
        categories[slug] = category

    Question.objects.filter(category__isnull=True).update(category=categories['qna'])


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_question_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pybo.category'),
        ),
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pybo.category'),
        ),
    ]
