# Generated by Codex on 2026-06-02

import django.db.models.deletion
from django.db import migrations, models


TARGET_TYPE_CHOICES = [
    ('question', '질문'),
    ('answer', '답변'),
    ('comment', '댓글'),
]


def populate_report_snapshots(apps, schema_editor):
    ContentReport = apps.get_model('pybo', 'ContentReport')

    reports = ContentReport.objects.select_related(
        'question',
        'question__author',
        'answer',
        'answer__author',
        'answer__question',
        'comment',
        'comment__author',
        'comment__question',
        'comment__answer',
        'comment__answer__question',
    )

    for report in reports:
        snapshot = None
        if report.question_id:
            snapshot = {
                'target_type': 'question',
                'target_object_id': report.question_id,
                'target_question_id': report.question_id,
                'target_author': report.question.author.username,
                'target_subject': report.question.subject,
                'target_content': report.question.content,
            }
        elif report.answer_id:
            snapshot = {
                'target_type': 'answer',
                'target_object_id': report.answer_id,
                'target_question_id': report.answer.question_id,
                'target_author': report.answer.author.username,
                'target_subject': report.answer.question.subject,
                'target_content': report.answer.content,
            }
        elif report.comment_id:
            question = report.comment.question or report.comment.answer.question
            snapshot = {
                'target_type': 'comment',
                'target_object_id': report.comment_id,
                'target_question_id': question.id,
                'target_author': report.comment.author.username,
                'target_subject': question.subject,
                'target_content': report.comment.content,
            }

        if snapshot is None:
            continue

        for field, value in snapshot.items():
            setattr(report, field, value)
        report.save(update_fields=list(snapshot.keys()))


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0011_question_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentreport',
            name='answer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reports',
                to='pybo.answer',
            ),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='comment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reports',
                to='pybo.comment',
            ),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='question',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reports',
                to='pybo.question',
            ),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='target_type',
            field=models.CharField(blank=True, choices=TARGET_TYPE_CHOICES, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='target_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='target_question_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='target_author',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='target_subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='target_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(populate_report_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contentreport',
            name='target_type',
            field=models.CharField(choices=TARGET_TYPE_CHOICES, max_length=20),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='target_object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='target_question_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='target_author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='target_subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='target_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='contentreport',
            constraint=models.UniqueConstraint(
                fields=('reporter', 'target_type', 'target_object_id'),
                name='unique_content_report_target',
            ),
        ),
    ]
